<nav class="navbar">
    <div class="nav-wrapper">
        <a href="#" class="brand-logo">
            <img src="img/logo.png" class="logo">
        </a>
        <ul class="nav-menu right hide-on-med-and-down">
            <li><a href="#">Acerca del evento</a></li>
            <li><a href="#">Expositores</a></li>
            <li><a href="#">Agenda</a></li>
            <li><a href="#">Auspiciadores</a></li>
            <li><a href="#">Registrarse</a></li>
        </ul>
    </div>
</nav>