<div class="sponsors-block" id="sponsors-block">
    <div class="container">
        <div class="row" data-container="sponsors">
            <h4 class="main-title">Auspiciadores</h4>

            <div class="col l3" data-template="sponsor">
                <a href="http://hivos.org" target="_blank" class="sponsor-logo" data-link="website">
                    <img src="img/hivos.png" alt="" data-image="logo">
                </a>
            </div>

        </div>
    </div>
</div>